import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const landingPage = readFileSync(new URL("../../../apps/web/app/page.tsx", import.meta.url), "utf8");
const agentationDev = readFileSync(new URL("../../../apps/web/app/agentation-dev.tsx", import.meta.url), "utf8");
const setupPage = readFileSync(new URL("../../../apps/web/app/setup/page.tsx", import.meta.url), "utf8");
const docsPage = readFileSync(new URL("../../../apps/web/app/docs/page.tsx", import.meta.url), "utf8");
const mcpClientTabs = readFileSync(new URL("../../../apps/web/app/mcp-client-tabs.tsx", import.meta.url), "utf8");
const mcpContent = readFileSync(new URL("../../../apps/web/app/mcp-content.ts", import.meta.url), "utf8");
const dashboardPage = readFileSync(new URL("../../../apps/web/app/dashboard/page.tsx", import.meta.url), "utf8");
const dashboardLedger = readFileSync(new URL("../../../apps/web/app/dashboard-ledger.ts", import.meta.url), "utf8");
const layout = readFileSync(new URL("../../../apps/web/app/layout.tsx", import.meta.url), "utf8");
const ogRoute = readFileSync(new URL("../../../apps/web/app/og/route.tsx", import.meta.url), "utf8");
const authConfirmRoute = readFileSync(new URL("../../../apps/web/app/auth/confirm/route.ts", import.meta.url), "utf8");
const confirmationTemplate = readFileSync(new URL("../../../supabase/email-templates/confirmation.html", import.meta.url), "utf8");
const magicLinkTemplate = readFileSync(new URL("../../../supabase/email-templates/magic-link.html", import.meta.url), "utf8");
const css = readFileSync(new URL("../../../apps/web/app/globals.css", import.meta.url), "utf8");

describe("web dashboard static wiring", () => {
  it("keeps the public landing page at the root route", () => {
    assert.match(landingPage, /ToolRouter/);
    assert.match(landingPage, /\/logo\.png/);
    assert.match(landingPage, /Tools your agent/);
    assert.match(landingPage, /Simplified billing/);
    assert.match(landingPage, /no\s+stablecoin\s+top-ups/);
    assert.match(landingPage, /Human boosts/);
    assert.match(landingPage, /free trials,\s+discounts,\s+or access paths/);
    assert.match(landingPage, /Get an API key/);
    assert.doesNotMatch(landingPage, /View console/);
    assert.doesNotMatch(landingPage, /Sign in/);
    assert.match(landingPage, /\/setup/);
    assert.match(landingPage, /\/docs/);
    assert.match(landingPage, /Hermes/);
    assert.match(landingPage, /OpenClaw/);
    assert.match(landingPage, /OpenJarvis/);
    assert.match(landingPage, /ZeroClaw/);
    assert.match(landingPage, /Codex/);
    assert.match(landingPage, /Claude/);
    assert.match(landingPage, /\/dashboard/);
    assert.match(landingPage, /\/v1\/status/);
    assert.match(landingPage, /publicEndpointStatus\(provider\)/);
    assert.match(landingPage, /statusReason\(provider\)/);
    assert.match(landingPage, /agentKitBenefit\(provider\)/);
    assert.match(landingPage, /Free trial/);
    assert.match(landingPage, /No credits required/);
    assert.match(landingPage, /Access unlock/);
    assert.match(landingPage, /Verified-human path/);
    assert.match(landingPage, /<div>Benefit<\/div>/);
    assert.match(landingPage, /Last check/);
    assert.match(landingPage, /Checked at least once/);
    assert.doesNotMatch(landingPage, /Fleet uptime/);
    assert.doesNotMatch(landingPage, /Last 30 days/);
    assert.doesNotMatch(landingPage, /<div>Path<\/div>/);
    assert.doesNotMatch(landingPage, /<div>Latency<\/div>/);
    assert.match(landingPage, /displayEndpointId\(provider\)/);
    assert.doesNotMatch(landingPage, /AgentKitStatusBadge/);
    assert.doesNotMatch(landingPage, /status-human-badge/);
    assert.match(landingPage, /<AgentationDev \/>/);
    assert.doesNotMatch(landingPage, /http:\/\/127\.0\.0\.1:9402/);
    assert.doesNotMatch(landingPage, /Get an MCP key/);
    assert.doesNotMatch(landingPage, /Pricing/);
    assert.doesNotMatch(landingPage, /Changelog/);
  });

  it("mounts Agentation on the public landing page in development", () => {
    assert.match(agentationDev, /"use client"/);
    assert.match(agentationDev, /import \{ Agentation \} from "agentation"/);
    assert.match(agentationDev, /process\.env\.NODE_ENV !== "development"/);
    assert.match(agentationDev, /<Agentation \/>/);
  });

  it("presents setup around generic tool categories before provider-specific endpoints", () => {
    const setupSurface = `${setupPage}\n${mcpClientTabs}\n${mcpContent}`;
    assert.match(setupPage, /<McpClientTabs \/>/);
    assert.match(setupSurface, /Connect your client/);
    assert.match(setupSurface, /https:\/\/toolrouter\.world/);
    assert.doesNotMatch(setupSurface, /localhost/);
    assert.doesNotMatch(setupSurface, /127\.0\.0\.1/);
    assert.doesNotMatch(setupSurface, /127\.0\.0\.1:9402/);
    assert.match(setupSurface, /Codex/);
    assert.match(setupSurface, /Claude Code/);
    assert.match(setupSurface, /claude mcp add --scope user/);
    assert.match(setupSurface, /codex mcp add/);
    assert.match(setupSurface, /Cursor/);
    assert.match(setupSurface, /VS Code/);
    assert.match(setupSurface, /Hermes/);
    assert.match(setupSurface, /OpenClaw/);
    assert.match(setupSurface, /@worldcoin\/toolrouter/);
    assert.match(setupSurface, /npx -y @worldcoin\/toolrouter/);
    assert.match(setupSurface, /Generate an API key, then replace/);
    assert.doesNotMatch(setupSurface, /do not need a local ToolRouter repo path/);
    assert.match(setupSurface, /~\/\.openclaw\/openclaw\.json/);
    assert.match(setupSurface, /\/reload-mcp/);
    assert.match(setupSurface, /hermes mcp test toolrouter/);
    assert.match(setupSurface, /role="tab"/);
    assert.match(setupSurface, /mcp-code-panel/);
    assert.match(setupPage, /Tool categories/);
    assert.match(setupPage, /search/);
    assert.match(setupPage, /browser use/);
    assert.match(setupPage, /toolrouter_list_categories/);
    assert.match(setupPage, /recommended endpoint/);
    assert.match(mcpContent, /First list the available ToolRouter tool categories/);
    assert.match(mcpContent, /include the ToolRouter request id/);
    assert.doesNotMatch(mcpContent, /restart/);
    assert.doesNotMatch(setupPage, /Available tools/);
  });

  it("keeps the operational dashboard on the dashboard route", () => {
    assert.match(dashboardPage, /Requests/);
    assert.match(dashboardPage, /Total paid/);
    assert.match(dashboardPage, /% using AgentKit/);
    assert.match(dashboardPage, /dashboardNavItems/);
    assert.match(dashboardPage, /dashboardNavLabel\(item\)/);
    assert.match(dashboardPage, /dashboardNavIcon\(item\)/);
    assert.match(dashboardPage, /className="topnav-tabs"/);
    assert.match(dashboardPage, /aria-label="Dashboard sections"/);
    assert.match(dashboardPage, /Verify your agent for benefits/);
    assert.match(dashboardPage, /Unlock AgentKit free trials,\s+discounts,\s+and access paths/);
    assert.match(dashboardPage, /Verify agent/);
    assert.match(dashboardPage, /AgentKit vs x402/);
    assert.match(dashboardPage, /successful\s+requests/);
    assert.doesNotMatch(dashboardPage, /on free\s+path/);
    assert.doesNotMatch(dashboardPage, /AgentKit \(free\)/);
    assert.doesNotMatch(dashboardPage, /x402 \(paid\)/);
    assert.doesNotMatch(dashboardPage, /% free/);
    assert.match(dashboardPage, /Recent calls/);
    assert.doesNotMatch(dashboardPage, /Filters/);
    assert.doesNotMatch(dashboardPage, /Endpoint registry/);
    assert.doesNotMatch(dashboardPage, /Supabase monitoring/);
    assert.match(dashboardPage, /Account Verification/);
    assert.match(dashboardPage, /Verify this account with AgentKit through World App/);
    assert.match(dashboardPage, /Verify with AgentKit/);
    assert.match(dashboardPage, /QRCodeSVG/);
    assert.match(dashboardPage, /Scan with World App/);
    assert.match(dashboardPage, /Open verification link/);
    assert.match(dashboardPage, /ToolRouter returned an unexpected response/);
    assert.match(dashboardPage, /World App verification returned an unexpected response/);
    assert.match(dashboardPage, /\/v1\/agentkit\/registration/);
    assert.match(dashboardPage, /\/v1\/agentkit\/registration\/complete/);
    assert.match(dashboardPage, /\/human\.svg/);
    assert.match(dashboardPage, /AgentKit - Enabled/);
    assert.match(dashboardPage, /human-badge-mark/);
    assert.match(dashboardPage, /endpointCell\(row\.endpoint_id\)/);
    assert.match(dashboardPage, /\/exa-logomark\.svg/);
    assert.match(dashboardPage, /\/browserbase-logomark\.svg/);
    assert.match(dashboardPage, /<th>Protocol<\/th>/);
    assert.match(dashboardPage, /<th>Benefit<\/th>/);
    assert.match(dashboardPage, /protocolChip\(row\)/);
    assert.match(dashboardPage, /benefitCell\(row\)/);
    assert.match(dashboardPage, /requestFailed\(row\)/);
    assert.match(dashboardPage, /statusTextClass\(row\)/);
    assert.match(dashboardPage, /compactRecentRequests\(requests\)/);
    assert.match(dashboardPage, /logicalRequestKey\(row\)/);
    assert.match(dashboardPage, /sameRecentX402Request\(row, other\)/);
    assert.match(dashboardPage, /AgentKit - \{label\}/);
    assert.doesNotMatch(dashboardPage, /<th>Value<\/th>/);
    assert.doesNotMatch(dashboardPage, /agentkit-value-kind/);
    assert.match(dashboardPage, /payment_protocol/);
    assert.match(dashboardPage, /MPP/);
    assert.doesNotMatch(dashboardPage, /isPaidAgentKitBenefit/);
    assert.match(dashboardPage, /isFreeTrial/);
    assert.match(dashboardPage, /path === "agentkit" && !row\.charged/);
    assert.match(dashboardPage, /Credit balance/);
    assert.match(dashboardPage, /\/v1\/top-ups\?limit=10/);
    assert.match(dashboardPage, /activeTopUps\.length \? \(/);
    assert.match(dashboardPage, /status === "funding_pending"/);
    assert.doesNotMatch(dashboardPage, /funding_failed[\s\S]*billing-notice/);
    assert.match(dashboardPage, /Credits usually appear within 30-90 seconds after\s+checkout/);
    assert.match(dashboardPage, /ToolRouter retries settlement/);
    assert.match(dashboardLedger, /top_up_settled: "Credits added"/);
    assert.match(dashboardPage, /Credit activity/);
    assert.match(dashboardPage, /compactLedgerEntries\(ledger\)/);
    assert.match(dashboardPage, /ledgerTypeLabel\(entry\.type\)/);
    assert.match(dashboardPage, /ledgerAmountPolarity\(entry\)/);
    assert.doesNotMatch(dashboardPage, /ledgerSourceCell/);
    assert.doesNotMatch(dashboardPage, /<th>Source<\/th>/);
    assert.doesNotMatch(dashboardPage, /<th>Reference<\/th>/);
    assert.match(dashboardPage, /copy-key-button/);
    assert.match(dashboardPage, /Copied/);
    assert.doesNotMatch(dashboardPage, /Payment address/);
    assert.doesNotMatch(dashboardPage, /Checkout created:/);
    assert.doesNotMatch(dashboardPage, /checkout_url\}`/);
    assert.doesNotMatch(dashboardPage, /Base USDC/);
    assert.doesNotMatch(dashboardPage, /Pending/);
    assert.doesNotMatch(dashboardPage, /Reserved/);
    assert.doesNotMatch(dashboardPage, /not verified/);
    assert.doesNotMatch(dashboardPage, /Not Verified/);
    assert.doesNotMatch(dashboardPage, /Check wallet/);
    assert.doesNotMatch(dashboardPage, /Check account against AgentKit/);
    assert.doesNotMatch(dashboardPage, /billing wallet/);
    assert.doesNotMatch(dashboardPage, /Endpoint operations/);
    assert.doesNotMatch(dashboardPage, /99\.4% \/ 24h/);
    assert.doesNotMatch(dashboardPage, /className="avatar"/);
  });

  it("uses dashboard session routes and resource-style router endpoints", () => {
    assert.match(dashboardPage, /NEXT_PUBLIC_TOOLROUTER_APP_URL/);
    assert.match(dashboardPage, /emailRedirectTo/);
    assert.match(dashboardPage, /\/v1\/dashboard\/requests/);
    assert.doesNotMatch(dashboardPage, /\/v1\/dashboard\/endpoints/);
    assert.match(dashboardPage, /\/v1\/api-keys/);
    assert.match(dashboardPage, /\/v1\/balance/);
    assert.match(dashboardPage, /\/v1\/agentkit\/account-verification/);
    assert.match(dashboardPage, /\/v1\/top-ups/);
    assert.match(mcpContent, /https:\/\/toolrouter\.world/);
    assert.match(dashboardPage, /<McpClientTabs apiKey=\{quickstartApiKey\} compact \/>/);
    assert.match(dashboardPage, /toolrouter\.dashboard\.apiKeys\.v1/);
    assert.match(dashboardPage, /toolrouter\.dashboard\.quickstartSeen\.v1/);
    assert.match(mcpClientTabs, /selectedCode/);
    assert.match(mcpClientTabs, /API key injected/);
    assert.match(mcpClientTabs, /API key needed/);
    assert.match(mcpClientTabs, /mcp-key-state/);
    assert.match(dashboardPage, /Set up MCP/);
    assert.match(dashboardPage, /Verify World ID/);
    assert.match(dashboardPage, /Generate an API key/);
    assert.match(dashboardPage, /Try it out/);
    assert.match(dashboardPage, /Copy prompt/);
    assert.doesNotMatch(dashboardPage, /Copy the prompt/);
    assert.match(dashboardPage, /maybeRouteFirstRun/);
    assert.match(dashboardPage, /#quickstart/);
    assert.match(mcpContent, /top sushi places in San Francisco/);
    assert.doesNotMatch(mcpContent, /toolrouter_search/);
    assert.doesNotMatch(dashboardPage, /AgentKit examples/);
    assert.doesNotMatch(dashboardPage, /endpoint_id: "exa\.search"/);
    assert.doesNotMatch(dashboardPage, /\/call/);
    assert.doesNotMatch(dashboardPage, /\/fetch/);
    assert.doesNotMatch(dashboardPage, /\/usage/);
  });

  it("keeps auth confirmation links on the ToolRouter domain", () => {
    assert.match(confirmationTemplate, /\/auth\/confirm\?token_hash=\{\{ \.TokenHash \}\}/);
    assert.match(confirmationTemplate, /type=signup/);
    assert.match(magicLinkTemplate, /\/auth\/confirm\?token_hash=\{\{ \.TokenHash \}\}/);
    assert.match(magicLinkTemplate, /type=magiclink/);
    assert.match(authConfirmRoute, /verifyOtp/);
    assert.match(authConfirmRoute, /token_hash/);
    assert.match(authConfirmRoute, /access_token/);
    assert.doesNotMatch(confirmationTemplate, /\.ConfirmationURL/);
    assert.doesNotMatch(magicLinkTemplate, /\.ConfirmationURL/);
    assert.doesNotMatch(magicLinkTemplate, /Your Magic Link/);
  });

  it("keeps the ToolRouter visual system in the Next app", () => {
    assert.match(css, /--bone/);
    assert.match(css, /\.mkt-hero/);
    assert.match(css, /\.topnav/);
    assert.match(css, /\.topnav-tabs/);
    assert.match(css, /\.topnav-tabs\s*\{[^}]*display:\s*none/);
    assert.match(css, /@media \(max-width: 1080px\)[\s\S]*\.topnav-tabs\s*\{[^}]*display:\s*flex/);
    assert.match(css, /@media \(max-width: 560px\)[\s\S]*\.topnav \.top-brand\s*\{[^}]*display:\s*none/);
    assert.match(css, /@media \(max-width: 560px\)[\s\S]*\.topnav-tabs \.icon\s*\{[^}]*display:\s*none/);
    assert.match(css, /\.verify-agent-banner/);
    assert.match(css, /@media \(max-width: 820px\)[\s\S]*\.verify-agent-banner\s*\{[^}]*flex-direction:\s*column/);
    assert.match(css, /\.recent-calls-table/);
    assert.match(css, /\.recent-calls-table tr\.request-row\.failed td/);
    assert.doesNotMatch(css, /\.status-human-badge/);
    assert.match(css, /\.billing-grid/);
    assert.match(css, /\.endpoint-cell\s*\{[^}]*display:\s*inline-flex/);
    assert.doesNotMatch(css, /\.endpoint-cell\s*\{[^}]*display:\s*grid/);
    assert.match(layout, /rel="icon"/);
    assert.match(layout, /\/logo\.png/);
  });

  it("serves path-specific OpenGraph images for public pages", () => {
    assert.match(layout, /metadataBase:\s*new URL\(appUrl\)/);
    assert.match(layout, /openGraph:/);
    assert.match(layout, /twitter:/);
    assert.match(layout, /\/og\?path=\//);
    assert.match(setupPage, /export const metadata/);
    assert.match(setupPage, /\/og\?path=\/setup/);
    assert.match(setupPage, /Connect any MCP-capable agent\./);
    assert.match(docsPage, /export const metadata/);
    assert.match(docsPage, /\/og\?path=\/docs/);
    assert.match(docsPage, /Ship endpoints agents can trust\./);
    assert.match(ogRoute, /ImageResponse/);
    assert.match(ogRoute, /routeCards/);
    assert.match(ogRoute, /Tools your agent can trust/);
    assert.doesNotMatch(ogRoute, /AgentKit \+ x402 tool routing/);
    assert.doesNotMatch(ogRoute, /Every endpoint is verified/);
    assert.match(ogRoute, /"\/setup"/);
    assert.match(ogRoute, /"\/docs"/);
    assert.match(ogRoute, /width:\s*1200/);
    assert.match(ogRoute, /height:\s*630/);
  });
});
